### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by canel-rom1** [Shubhamvis98/kali-pinephone#7]
How do you compile the image? Thank you

**Comment by orhun** [comment]
I asked the same question in #2

**Comment by Shubhamvis98** [comment]
> I asked the same question in #2

@orhun 
## run on an arch64 machine as x86_64 host takes more time
Step 1: `debootstrap kali-rolling rootfs http://http.kali.org/kali`
Step 2: mount and chroot into rootfs using: chroot rootfs bash -l
Step 3: install necessary packages eg kernel phosh network-manager u-boot etcetera
Step 4: check if u-boot configs, dtbs and /etc/fstab files are correct, otherwise it won't boot
Step 5: in u-boot's boot config, you must have to mention fdtdir, by default its not present in the config
After that you can create a flashable img. If you're using Tow-Boot then no need to merge u-bootloader. I personally suggest you to use Tow-Boot.
I hope this will help.

I'll try to upload an automated script to build these images but right now kali repository doesn't have pinephone's kernel and also some configs that needs to be present in pinephone like placing dtbs in boot partition etc.

**Comment by orhun** [comment]
Having a script for building the image would be really nice! I can help with automated builds (via GitHub Workflow) if you can provide a script 🐻

**Comment by Shubhamvis98** [comment]
> Having a script for building the image would be really nice! I can help with automated builds (via GitHub Workflow) if you can provide a script bear

Thanks, Mate. I already made one. And also working with some devs. There is a surprise for PP users that's why I'm not updating it right now.

**Comment by Jac-Apex-Team** [comment]
@Shubhamvis98 
hello, I keep having problems installing Kali linux on a PinePhone, every time I can't make the bootable image. Can you explain step by step please? or to put a fully functional image? 

I followed the installation guide, but without success.

**Comment by Shubhamvis98** [comment]
> @Shubhamvis98 hello, I keep having problems installing Kali linux on a PinePhone, every time I can't make the bootable image. Can you explain step by step please? or to put a fully functional image?
> 
> I followed the installation guide, but without success.

If you can put the commands here or the installation process then maybe I can help.

**Comment by Shubhamvis98** [comment]
@Jac-Apex-Team @orhun @canel-rom1 
I updated the repo, but it is not very optimized. But you can execute the "pinephone.sh", it'll generate a working minimal pinephone image. You can make changes to the funcs file. Let me know if you need any help. I'll try to be here this weekend. ( ;

**Comment by orhun** [comment]
> Officially released kali for pinephone and pro. Checkout the blog here [kali.org/blog/kali-linux-2022-4-release](https://www.kali.org/blog/kali-linux-2022-4-release/)

Does that mean this repo is obsolete now?

**Comment by Shubhamvis98** [comment]
> > Officially released kali for pinephone and pro. Checkout the blog here [kali.org/blog/kali-linux-2022-4-release](https://www.kali.org/blog/kali-linux-2022-4-release/)
> 
> Does that mean this repo is obsolete now?

I'm also thinking about the same. As I also worked on that official nethunter release.
What do you think?

**Comment by orhun** [comment]
> > > Officially released kali for pinephone and pro. Checkout the blog here [kali.org/blog/kali-linux-2022-4-release](https://www.kali.org/blog/kali-linux-2022-4-release/)
> > 
> > 
> > Does that mean this repo is obsolete now?
> 
> I'm also thinking about the same. As I also worked on that official nethunter release. What do you think? Should I stop creating my releases?

I think it is good to have this repository in case someone wants to build their own image from scratch. It might be an alternative solution for using Kali on Pinephone. You can link to the official release in README.md.

However, if you think maintaining this will be a burden for you in the long term, you can simply archive the repository.

**Comment by Shubhamvis98** [comment]
I was thinking to maintain this as I mostly use my own builds everywhere, even on my PC and raspberrypi as well.

**Comment by orhun** [comment]
Sounds good! Thanks for your efforts, it's really a good project 💖

**Comment by Shubhamvis98** [comment]
Thanks, Mate (-;
