### ISSUE TITLE
PinePhone Pro not showing GUI

### ISSUE THREAD

**Issue by glaucobonomo** [Shubhamvis98/kali-pinephone#8]
hello, i've tried installing kali nethunter on a PinePhone Pro but when i boot into it, it opens all apps, not showing an idle screen, the three buttons at the bottom do not work, and i don't have the nethunter app, only thing is the terminal that let me access to kali system.
how can i fix this? did anyone had my same issue?
i've tried rewriting the image to the sd different times but nothing changes, plus if i update the system from the software app, it rech around 50%, then it reboots, after that i can no longer log in with default kali - 1234 and i have to rewrite the image cause i can't do anything... please help

**Comment by Shubhamvis98** [comment]
Hi @glaucobonomo,
Thanks for trying the image. The image is correct, and you flashed it right. There will be no nethunter app because, unlike android, pinephone is running Kali as the host OS. By default, there is no idle screen, you have to press ESC key to go to the idle screen.
Please let me know if you have any other queries.

**Comment by Shubhamvis98** [comment]
and for the update, please use "apt update && apt upgrade -y" this will update the OS.
Suppose you have a raspberry pi with Kali installed on it. It's pure Kali Linux, not a chroot container in android.

**Comment by glaucobonomo** [comment]
ok thank you so much, i thought about it later that was not android so that was why there was no app, thanks for confirming that. all working good for now thanks again
